package de.datenwissen.thesaurus.vocabularies;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://www.w3.org/2009/08/skos-reference/skos-xl.rdf 
 * @author Auto-generated by schemagen on 26 Okt 2010 17:08 
 */
public class SKOS_XL {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2008/05/skos-xl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>If C skosxl:altLabel L and L skosxl:literalForm V, then X skos:altLabel V.</p> */
    public static final Property altLabel = m_model.createProperty( "http://www.w3.org/2008/05/skos-xl#altLabel" );
    
    /** <p>If C skosxl:hiddenLabel L and L skosxl:literalForm V, then C skos:hiddenLabel 
     *  V.</p>
     */
    public static final Property hiddenLabel = m_model.createProperty( "http://www.w3.org/2008/05/skos-xl#hiddenLabel" );
    
    public static final Property labelRelation = m_model.createProperty( "http://www.w3.org/2008/05/skos-xl#labelRelation" );
    
    /** <p>The range of skosxl:literalForm is the class of RDF plain literals.If two 
     *  instances of the class skosxl:Label have the same literal form, they are not 
     *  necessarily the same resource.</p>
     */
    public static final Property literalForm = m_model.createProperty( "http://www.w3.org/2008/05/skos-xl#literalForm" );
    
    /** <p>If C skosxl:prefLabel L and L skosxl:literalForm V, then X skos:prefLabel 
     *  V.</p>
     */
    public static final Property prefLabel = m_model.createProperty( "http://www.w3.org/2008/05/skos-xl#prefLabel" );
    
    public static final Resource Label = m_model.createResource( "http://www.w3.org/2008/05/skos-xl#Label" );
    
}
